### PR TITLE
Add missing resources to site package

### PR DESCRIPTION
**Pull request by astefanutti**
Follow-up on openshift/origin-web-console#469.

### CODE REVIEW

**Comment by jimmidyson** [comment]
@astefanutti `bower ECONFLICT     Unable to find suitable version for angular`

**Comment by astefanutti** [comment]
@jimmidyson thanks. That's Bower manual prompt that's not available on CI. Let me fix the Angular version and repush.

**Comment by astefanutti** [comment]
@jimmidyson it's been fixed.

**Comment by jimmidyson** [comment]
Confident this fixes the regression?

**Comment by astefanutti** [comment]
Quite confident.

**Comment by jimmidyson** [comment]
Guess this needs releasing? Can you do that or want me to? Or is there stuff to do before that?

**Comment by astefanutti** [comment]
Yes, then we can notify the OpenShift Web console team so that they can give it a try. And hopefully they won't find any other issues.

That being said, I have no idea what's the release process here and I imagine I won't have the permissions. I'm afraid I'm pretty useless at that point.

**Comment by jimmidyson** [comment]
OK I'll release it - iirc it's just a tag & bower does what it needs to with that... I'll remember soon enough.

**Comment by gashcrumb** [comment]
Fyi to release just `bower version patch` and then `git push && git push
--tags`, give it a couple minutes and you'll have a new `-build` tag and
release on github available.

**Comment by jimmidyson** [comment]
Done - @astefanutti can you let the openshift team know? Thanks!

**Comment by jwforres** [comment]
Was already following this thread :)  1.0.46 right?

**Comment by jwforres** [comment]
nvm got confirmation from @jimmidyson on irc

**Comment by jimmidyson** [comment]
@jwforres Sneaky! Yeah 1.0.46 it is.

**Pull request merged**
